version: "3"
services:
  backend:
    build: ./cmd_system/
    command: >
      sh -c "python manage.py makemigrations catalog && 
              python manage.py migrate && 
              python manage.py runserver 0.0.0.0:7000"
    volumes:
      - ./cmd_system:/code
    ports:
      - "7000:7000"

  frontend:
    build:
      context: ./frontend/
    ports:
      - '3000:3000'
